[[input]]
data = 'path/to/spectrum'
opacities = 'path/to/opacities'
output = 'path/to/output'


[[observation type]]
observation_type = 'emission' #other options are 'transmission' or 'imaging'

'''
[[planet properties]]
planet = {
    radius={value=1.2, unit='Rjup'}, 
    mass ={value=1.2, unit='Mjup'},
    g={value=1e4, unit='cm/s**2'},
    distance={value=10, unit='parsec'},
    separation={value=200, unit='AU'},
    T_eff={value=500, unit='Kelvin'}
}


#[star properties]
star={
    radius={value=1, unit='Rsun'}, 
    temperature={value=5400, unit='Kelvin'}
}


#[temperature profile]
pressure={
    minimum = 1e-7,
    maximum = 1e3,
    reference = 1e1,
    n_layers = 100
}


temperature={
    'profile' = 'isothermal', #other options are 'spline', 'madhu_seager_09', 'guillot', 'zj_24', 'molliere_20', 'Kitzman_20', 'sonora_bobcat'...
    #isothermal
    'T' = 500,
    #spline
    'n_T_points'=6,
    'T'=[1000, 700, 400, 300, 250, 200],
    #madhu_seager_09
    'P_0'=,
    'P_1'=,
    'P_2'=,
    'P_3'=,
    'T_0'=,
    'T_2'=,
    'T_3'=
    'alpha_1'=,
    'alpha_2'=,
    'beta_1'=,
    'beta_2'=
}


### CHEMISTRY ###
chemistry_type='free' #other options are 'chem_eq', ...
abundances={
    'H2'={mix_rat=0.85},
    'He'={mix_rat=0.15},
    'H2O'={mix_rat=1e-4},
    'CH4'={mix_rat_1=1e-4, mix_rat_2=1e-3, p=1e-2},
    'NH3'={mix_rat=1e-4}
}
'''
